import { type RouteConfig, index, route } from "@react-router/dev/routes";

// Every page of the blog (ADR-06: new routes are also registered in app/data/routes.ts).
export default [
	index("routes/home.tsx"),
	route("about", "routes/about.tsx"),
	route("contact", "routes/contact.tsx"),
	route("faq", "routes/faq.tsx"),
	route("pricing", "routes/pricing.tsx"),
	route("privacy", "routes/privacy.tsx"),
	route("login", "routes/login.tsx"),
	route("signup", "routes/signup.tsx"),
	route("blog", "routes/blog._index.tsx"),
	route("blog/:slug", "routes/blog.$slug.tsx"),
	route("temas", "routes/temas._index.tsx"),
	route("temas/:slug", "routes/temas.$slug.tsx"),
	route("mapas", "routes/mapas.tsx"),
	route("guias", "routes/guias.tsx"),
	route("evidencias", "routes/evidencias.tsx"),
	route("buscar", "routes/buscar.tsx"),
	route("prisma", "routes/prisma.tsx"),
	route("loja", "routes/loja._index.tsx"),
	route("loja/:type", "routes/loja.$type._index.tsx"),
	route("loja/:type/:slug", "routes/loja.$type.$slug.tsx"),
	route("admin", "routes/admin._index.tsx"),
	route("admin/design-system", "routes/admin.design-system.tsx"),
	route("admin/handoff", "routes/admin.handoff.tsx"),
	route("admin/relatorio-exemplo", "routes/admin.relatorio-exemplo.tsx"),
	route("admin/rotas", "routes/admin.rotas.tsx"),
	route("rss.xml", "routes/rss[.]xml.ts"),
	route("sitemap-index.xml", "routes/sitemap-index[.]xml.ts"),
	route("sitemap-0.xml", "routes/sitemap-0[.]xml.ts"),
	route("*", "routes/$.tsx"),
] satisfies RouteConfig;
