import {
	BarChart3,
	BookOpen,
	Calendar,
	FileText,
	GitBranch,
	Globe,
	Image,
	Info,
	LayoutDashboard,
	Lightbulb,
	ListChecks,
	Mail,
	MessageSquare,
	PenLine,
	Search,
	Settings,
	Share2,
	ShieldCheck,
	Smartphone,
	Tags,
	Video,
	Layers,
	type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
	dashboard: LayoutDashboard,
	blog: Globe,
	content: FileText,
	brief: BookOpen,
	arguments: MessageSquare,
	evidence: ShieldCheck,
	production: PenLine,
	assets: Layers,
	visuals: Image,
	ytlong: Video,
	shorts: Smartphone,
	social: Share2,
	newsletter: Mail,
	seo: Search,
	calendar: Calendar,
	distribution: GitBranch,
	performance: BarChart3,
	backlog: Lightbulb,
	taxonomy: Tags,
	decisions: ListChecks,
	config: Settings,
	sobre: Info,
};
