// Static pages of the site (sitemap + prerender). Blog articles are added from content/blog.
export const PAGES = [
	"/",
	"/about/",
	"/admin/",
	"/admin/design-system/",
	"/admin/relatorio-exemplo/",
	"/admin/rotas/",
	"/blog/",
	"/contact/",
	"/faq/",
	"/login/",
	"/pricing/",
	"/privacy/",
	"/signup/",
] as const;

/** Endpoints generated by the site (not HTML pages). */
export const ENDPOINTS = ["/rss.xml", "/sitemap-index.xml", "/sitemap-0.xml"] as const;
