// Static pages of the site (sitemap + prerender). Blog articles are added from content/blog.
import seed from "./editorial/seed.json";

export const PAGES = [
	"/",
	"/about/",
	"/admin/",
	"/admin/design-system/",
	"/admin/handoff/",
	"/admin/relatorio-exemplo/",
	"/admin/rotas/",
	"/blog/",
	"/buscar/",
	"/contact/",
	"/evidencias/",
	"/faq/",
	"/guias/",
	"/login/",
	"/loja/",
	"/mapas/",
	"/pricing/",
	"/prisma/",
	"/privacy/",
	"/signup/",
	"/temas/",
] as const;

/** One page per territory of the editorial taxonomy (TAX-RC-*): /temas/<slug>/. */
export const TERRITORY_PATHS: string[] = seed.seed.taxonomy.map(
	(t) => `/temas/${String(t.Slug).replace(/^\/|\/$/g, "")}/`,
);

/** Endpoints generated by the site (not HTML pages). */
export const ENDPOINTS = ["/rss.xml", "/sitemap-index.xml", "/sitemap-0.xml"] as const;
