import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import QRCode from "qrcode";
import { ListChecks, PanelsTopLeft, ArrowRight } from "lucide-react";
import "./miniapp.css";
import { demoPlan } from "./demoPlan";

type WorkType = "project" | "study" | "service" | "other" | "unspecified";
type WindowKind = "morning" | "afternoon" | "evening" | "custom" | "unspecified";
type Day = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
type Action = { id: string; order: number; verb: string; text: string; state: "suggested" | "accepted" | "blocked" | "completed"; origin: "template" | "user" | "imported" };
export type Plan = { schema_version: "1.0.0"; mode: "personal" | "blank" | "demo"; user: { display_name: string }; work: { type: WorkType; other_label: string; title: string }; routine: { window: WindowKind; exact_start: string | null; exact_end: string | null; days: Day[]; duration_minutes: number | null; preference: string }; goal: string; actions: Action[]; qr: { url: string }; metadata: { source_kind: "user_input" | "demo_fixture" | "imported" | "blank_template"; app_id: "EXEC-MINIAPP-001"; created_at: string | null; original_source_id: string | null } };
const KEY = "executar-processo-prisma-v1";
const dayOptions: [Day, string][] = [["mon", "Seg"], ["tue", "Ter"], ["wed", "Qua"], ["thu", "Qui"], ["fri", "Sex"], ["sat", "Sáb"], ["sun", "Dom"]];
const fresh = (blank = false): Plan => ({ schema_version: "1.0.0", mode: blank ? "blank" : "personal", user: { display_name: "" }, work: { type: "unspecified", other_label: "", title: "" }, routine: { window: "unspecified", exact_start: null, exact_end: null, days: [], duration_minutes: null, preference: "" }, goal: "", actions: blank ? [] : ["Definir o resultado", "Organizar a sequência", "Preparar os materiais"].map((text, i) => ({ id: `ACT-${String(i + 1).padStart(2, "0")}`, order: i + 1, verb: text.split(" ")[0], text, state: "suggested", origin: "template" })), qr: { url: "" }, metadata: { source_kind: blank ? "blank_template" : "user_input", app_id: "EXEC-MINIAPP-001", created_at: new Date().toISOString(), original_source_id: null } });
const normalizeUrl = (value: string) => { try { const url = new URL(value.trim()); return ["http:", "https:"].includes(url.protocol) && value.length <= 2048 ? url.toString() : ""; } catch { return ""; } };
function validPlan(value: unknown): value is Plan {
 if (!value || typeof value !== "object") return false;
 const p = value as Plan;
 const keysAre = (obj: object, keys: string[]) => Object.keys(obj).length === keys.length && keys.every(key => Object.hasOwn(obj, key));
 const keysWithin = (obj: object, required: string[], allowed: string[]) => required.every(key => Object.hasOwn(obj, key)) && Object.keys(obj).every(key => allowed.includes(key));
 const enums = (v: unknown, allowed: string[]) => typeof v === "string" && allowed.includes(v);
 return keysAre(p, ["schema_version", "mode", "user", "work", "routine", "goal", "actions", "qr", "metadata"]) && keysAre(p.user, ["display_name"]) && keysAre(p.work, ["type", "other_label", "title"]) && keysAre(p.routine, ["window", "exact_start", "exact_end", "days", "duration_minutes", "preference"]) && keysAre(p.qr, ["url"]) && keysWithin(p.metadata, ["source_kind", "app_id"], ["source_kind", "app_id", "created_at", "original_source_id"]) && p.schema_version === "1.0.0" && enums(p.mode, ["personal", "blank", "demo"]) && !!p.user && typeof p.user.display_name === "string" && p.user.display_name.length <= 80 && !!p.work && enums(p.work.type, ["project", "study", "service", "other", "unspecified"]) && typeof p.work.other_label === "string" && p.work.other_label.length <= 120 && typeof p.work.title === "string" && p.work.title.length <= 120 && !!p.routine && enums(p.routine.window, ["morning", "afternoon", "evening", "custom", "unspecified"]) && (p.routine.exact_start === null || typeof p.routine.exact_start === "string" && /^([01]\d|2[0-3]):[0-5]\d$/.test(p.routine.exact_start)) && (p.routine.exact_end === null || typeof p.routine.exact_end === "string" && /^([01]\d|2[0-3]):[0-5]\d$/.test(p.routine.exact_end)) && Array.isArray(p.routine.days) && new Set(p.routine.days).size === p.routine.days.length && p.routine.days.every(d => enums(d, dayOptions.map(([key]) => key))) && (p.routine.duration_minutes === null || Number.isInteger(p.routine.duration_minutes) && p.routine.duration_minutes >= 1 && p.routine.duration_minutes <= 1440) && typeof p.routine.preference === "string" && p.routine.preference.length <= 160 && typeof p.goal === "string" && p.goal.length <= 500 && Array.isArray(p.actions) && p.actions.length <= 30 && new Set(p.actions.map(a => a.id)).size === p.actions.length && p.actions.every(a => typeof a.id === "string" && /^ACT-\d{2,3}$/.test(a.id) && Number.isInteger(a.order) && a.order > 0 && keysAre(a, ["id", "order", "verb", "text", "state", "origin"]) && typeof a.verb === "string" && a.verb.length > 0 && a.verb.length <= 50 && typeof a.text === "string" && a.text.length > 0 && a.text.length <= 240 && enums(a.state, ["suggested", "accepted", "blocked", "completed"]) && enums(a.origin, ["template", "user", "imported"])) && !!p.qr && typeof p.qr.url === "string" && p.qr.url.length <= 2048 && !!p.metadata && enums(p.metadata.source_kind, ["user_input", "demo_fixture", "imported", "blank_template"]) && p.metadata.app_id === "EXEC-MINIAPP-001" && (p.metadata.created_at === null || typeof p.metadata.created_at === "string") && (p.metadata.original_source_id === null || typeof p.metadata.original_source_id === "string");
}
function migrateLegacy(value: unknown): Plan | null {
 if (!value || typeof value !== "object") return null;
 const old = value as Record<string, unknown>;
 if (validPlan(old)) return { ...old, metadata: { ...old.metadata, source_kind: "imported", created_at: old.metadata.created_at ?? null, original_source_id: old.metadata.original_source_id ?? null } };
 if (old.version !== "1.0.0" || !Array.isArray(old.tasks)) return null;
 const p = fresh(); p.metadata.source_kind = "imported"; p.work.title = typeof old.name === "string" ? old.name.slice(0, 120) : ""; p.routine.preference = typeof old.context === "string" ? old.context.slice(0, 160) : ""; p.goal = typeof old.goal === "string" ? old.goal.slice(0, 500) : ""; p.qr.url = typeof old.url === "string" ? old.url.slice(0, 2048) : "";
 p.actions = old.tasks.slice(0, 30).flatMap((item, i) => { if (!item || typeof item !== "object") return []; const t = item as Record<string, unknown>; if (typeof t.text !== "string" || !t.text.trim()) return []; return [{ id: `ACT-${String(i + 1).padStart(2, "0")}`, order: i + 1, verb: t.text.trim().split(/\s+/)[0].slice(0, 50), text: t.text.trim().slice(0, 240), state: t.accepted === true ? "accepted" as const : "suggested" as const, origin: "imported" as const }]; });
 if (typeof old.window === "string") p.routine.window = ({ Manhã: "morning", Tarde: "afternoon", Noite: "evening" } as Record<string, WindowKind>)[old.window] ?? "unspecified";
 return p;
}
export function ProcessWorkApp() {
 const [plan, setPlan] = useState(fresh), [step, setStep] = useState(0), [screen, setScreen] = useState<"intro" | "form" | "result">("intro"), [view, setView] = useState<"process" | "prisma">("process"), [qr, setQr] = useState(""), [save, setSave] = useState(false), [message, setMessage] = useState("");
 useEffect(() => { try { const raw = localStorage.getItem(KEY); if (raw) { const parsed = migrateLegacy(JSON.parse(raw)); if (parsed) { setPlan(parsed); setSave(true); } } } catch { /* local data may be malformed */ } if ("serviceWorker" in navigator) navigator.serviceWorker.register("/ferramentas/processo-de-trabalho/sw.js", { scope: "/ferramentas/processo-de-trabalho/" }).then(() => navigator.serviceWorker.ready).then(reg => { const urls = performance.getEntriesByType("resource").map(x => x.name).filter(x => { try { return new URL(x).origin === location.origin; } catch { return false; } }); reg.active?.postMessage({ type: "CACHE_URLS", urls }); }).catch(() => undefined); }, []);
 useEffect(() => { if (save) try { localStorage.setItem(KEY, JSON.stringify(plan)); } catch { setMessage("Não foi possível salvar neste dispositivo."); } }, [plan, save]);
 useEffect(() => { const url = normalizeUrl(plan.qr.url); if (!url) { setQr(""); return; } let current = true; QRCode.toDataURL(url, { margin: 4, width: 220, errorCorrectionLevel: "M" }).then(data => current && setQr(data)).catch(() => setQr("")); return () => { current = false; }; }, [plan.qr.url]);
 const patch = (updater: (current: Plan) => Plan) => setPlan(current => updater(current));
 const sorted = useMemo(() => [...plan.actions].sort((a, b) => a.order - b.order), [plan.actions]);
 const setAction = (id: string, changes: Partial<Action>) => patch(p => ({ ...p, actions: p.actions.map(a => a.id === id ? { ...a, ...changes } : a) }));
 const addAction = () => patch(p => p.actions.length >= 30 ? p : { ...p, actions: [...p.actions, { id: `ACT-${String(Math.max(0, ...p.actions.map(a => Number(a.id.slice(4)) || 0)) + 1).padStart(2, "0")}`, order: p.actions.length + 1, verb: "Definir", text: "Definir próxima ação", state: "suggested", origin: "user" }] });
 const move = (id: string, delta: number) => patch(p => { const items = [...p.actions].sort((a, b) => a.order - b.order); const i = items.findIndex(a => a.id === id), j = i + delta; if (j < 0 || j >= items.length) return p; [items[i], items[j]] = [items[j], items[i]]; return { ...p, actions: items.map((a, order) => ({ ...a, order: order + 1 })) }; });
 const importJson = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = migrateLegacy(JSON.parse(await file.text())); if (!parsed) throw new Error("O arquivo não corresponde ao MiniAppPlan v1 nem ao formato legado reconhecido."); setPlan(parsed); setScreen("form"); setStep(3); setMessage("JSON validado e importado."); } catch (error) { setMessage(error instanceof Error ? error.message : "Arquivo inválido."); } finally { event.target.value = ""; } };
 const exportJson = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(plan, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = "executar-miniapp-plan-v1.json"; a.click(); URL.revokeObjectURL(url); };
 const labels: Record<WorkType, string> = { project: "Projeto", study: "Estudo", service: "Serviço", other: "Outro", unspecified: "Não definir" };
 const windowLabels: Record<WindowKind, string> = { morning: "Manhã", afternoon: "Tarde", evening: "Noite", custom: "Personalizar", unspecified: "Não definir" };
 const actionList = <ol className="miniapp-plan-actions">{sorted.map((action, index) => <li key={action.id}><b>{action.verb}</b>{action.text.startsWith(action.verb) ? action.text.slice(action.verb.length) : ` ${action.text}`}<small> · {action.state === "accepted" ? "ACEITA" : action.state === "completed" ? "CONCLUÍDA" : action.state === "blocked" ? "PENDENTE" : "SUGERIDA"}</small></li>)}</ol>;
 const sheet = <article className={`miniapp-sheet ${view}`}><header><small>EXECUTAR · {plan.mode === "demo" ? "DEMONSTRAÇÃO" : "PROCESSO DE TRABALHO"}</small><h2>{plan.work.title || "Processo de trabalho"}</h2><p>{plan.user.display_name || ""}{plan.user.display_name && " · "}{labels[plan.work.type]}{plan.work.type === "other" && plan.work.other_label ? `: ${plan.work.other_label}` : ""}</p></header>{view === "process" ? <><h3>Resultado esperado</h3><p>{plan.goal || "A DEFINIR"}</p><p>{windowLabels[plan.routine.window]}{plan.routine.exact_start ? ` · ${plan.routine.exact_start}–${plan.routine.exact_end ?? ""}` : ""}{plan.routine.days.length ? ` · ${plan.routine.days.map(d => dayOptions.find(([key]) => key === d)?.[1]).join(", ")}` : ""}{plan.routine.duration_minutes ? ` · ${plan.routine.duration_minutes} min` : ""}</p><p>{plan.routine.preference}</p>{actionList}</> : <div className="miniapp-faces"><section><small>FACE 01 · VISÃO</small><h3>{plan.goal || "Resultado desejado"}</h3><p>{plan.work.title || "Processo de trabalho"}</p><p>{plan.routine.preference}</p></section><section><small>FACE 02 · EXECUÇÃO</small>{actionList}</section><section><small>FACE 03 · PRÓXIMO PASSO + QR</small><p>{plan.actions.find(a => a.state === "accepted" || a.state === "suggested")?.text || "Defina o próximo passo"}</p>{qr ? <img width="120" src={qr} alt="QR gerado localmente" /> : <p>QR opcional</p>}<p>{plan.qr.url || "Link não informado"}</p></section></div>}</article>;
 const chip = (label: string, active: boolean, onClick: () => void) => <button type="button" className={active ? "mini-chip active" : "mini-chip"} aria-pressed={active} onClick={onClick}>{label}</button>;
 return <div className="miniapp-root">
 {screen === "intro" && <section className="miniapp-intro" aria-labelledby="miniapp-title">
 <header className="miniapp-hero"><div><p className="eyebrow">EXECUTAR · FERRAMENTAS</p><h1 id="miniapp-title">Processo de Trabalho + Prisma</h1></div><p className="miniapp-lead">Organize uma rotina, revise as ações e imprima o Prisma A4. Sem conta e sem envio dos dados.</p></header>
 <div className="miniapp-feature-grid">
 <article className="panel panel-subtle miniapp-feature"><span className="miniapp-feature-icon" aria-hidden="true"><ListChecks /></span><h2>Organize seu processo</h2><p>Defina seu trabalho, escolha os horários e revise uma sequência de ações que caiba na sua rotina.</p><div className="miniapp-sample" aria-label="Prévia das quatro etapas"><p className="eyebrow">DO OBJETIVO À AÇÃO</p><ol>{["Seu trabalho", "Ritmo e disponibilidade", "Resultado desejado", "Sequência de ações"].map((title, i) => <li key={title}><span className="miniapp-number">0{i + 1}</span><span>{title}</span></li>)}</ol></div><button className="btn btn-primary mini-primary" onClick={() => { setPlan(fresh()); setScreen("form"); setStep(0); }}>Iniciar <ArrowRight size={16} aria-hidden="true" /></button></article>
 <article className="panel panel-subtle miniapp-feature"><span className="miniapp-feature-icon" aria-hidden="true"><PanelsTopLeft /></span><h2>Leve seu plano para o papel</h2><p>Confira o processo ou as três faces do Prisma. Imprima em A4 e use um QR para acessar seu próximo passo.</p><div className="miniapp-sample miniapp-prisma-sample" aria-label="Prévia das faces do Prisma"><p className="eyebrow">PRISMA A4 · TRÊS FACES</p>{["Visão", "Execução", "Próximo passo + QR"].map((title, i) => <div key={title}><span className="miniapp-number">0{i + 1}</span><strong>{title}</strong></div>)}</div><button className="btn btn-primary mini-primary" onClick={() => { setPlan(demoPlan); setView("process"); setScreen("result"); }}>Ver exemplo preenchido</button></article>
 </div>
 <div className="panel miniapp-utilities"><div><h2>Continue de onde parou</h2><p>Use um template vazio ou importe um plano salvo.</p></div><div className="miniapp-actions"><button className="btn btn-secondary" onClick={() => { setPlan(fresh(true)); setView("process"); setScreen("result"); }}>Template vazio</button><a className="miniapp-download-link" href="/ferramentas/processo-de-trabalho/exemplo-miniapp-plan-v1.json" download>Baixar JSON do exemplo</a><details><summary>Restaurar arquivo</summary><label>Importar JSON<input type="file" accept=".json,application/json" onChange={importJson} /></label></details></div></div>
 </section>}
 {screen === "form" && <section className="miniapp-main"><div className="panel miniapp-panel"><div className="miniapp-step"><p className="eyebrow" aria-live="polite">ETAPA {step + 1} DE 4</p><button onClick={() => { setView(view === "process" ? "prisma" : "process"); }}>Prévia: {view === "process" ? "Processo" : "Prisma"}</button></div>
 {step === 0 && <><h2>Seu trabalho</h2><label>Nome (opcional)<input maxLength={80} value={plan.user.display_name} onChange={e => patch(p => ({ ...p, user: { display_name: e.target.value } }))} /></label><label>Título (opcional)<input maxLength={120} value={plan.work.title} onChange={e => patch(p => ({ ...p, work: { ...p.work, title: e.target.value } }))} /></label><fieldset><legend>Tipo de trabalho</legend><div className="miniapp-chips">{(["project", "study", "service", "other", "unspecified"] as WorkType[]).map(type => chip(labels[type], plan.work.type === type, () => patch(p => ({ ...p, work: { ...p.work, type } }))))}</div></fieldset>{plan.work.type === "other" && <label>Qual tipo?<input maxLength={120} value={plan.work.other_label} onChange={e => patch(p => ({ ...p, work: { ...p.work, other_label: e.target.value } }))} /></label>}</>}
 {step === 1 && <><h2>Ritmo e disponibilidade</h2><fieldset><legend>Janela do dia</legend><div className="miniapp-chips">{(["morning", "afternoon", "evening", "custom", "unspecified"] as WindowKind[]).map(kind => chip(windowLabels[kind], plan.routine.window === kind, () => patch(p => ({ ...p, routine: { ...p.routine, window: kind } }))))}</div></fieldset>{plan.routine.window === "custom" && <div className="miniapp-actions"><label>Início<input type="time" value={plan.routine.exact_start ?? ""} onChange={e => patch(p => ({ ...p, routine: { ...p.routine, exact_start: e.target.value || null } }))} /></label><label>Fim<input type="time" value={plan.routine.exact_end ?? ""} onChange={e => patch(p => ({ ...p, routine: { ...p.routine, exact_end: e.target.value || null } }))} /></label></div>}<fieldset><legend>Dias disponíveis</legend><div className="miniapp-chips">{dayOptions.map(([day, label]) => chip(label, plan.routine.days.includes(day), () => patch(p => ({ ...p, routine: { ...p.routine, days: p.routine.days.includes(day) ? p.routine.days.filter(d => d !== day) : [...p.routine.days, day] } }))))}</div></fieldset><label>Duração estimada<select value={plan.routine.duration_minutes ?? ""} onChange={e => patch(p => ({ ...p, routine: { ...p.routine, duration_minutes: e.target.value ? Number(e.target.value) : null } }))}><option value="">Não definir</option><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="60">1 hora</option><option value="90">1h30</option><option value="120">2 horas</option><option value="180">Personalizar</option></select></label>{plan.routine.duration_minutes === null ? null : ![15,30,60,90,120].includes(plan.routine.duration_minutes) && <label>Minutos (1 a 1440)<input type="number" min={1} max={1440} value={plan.routine.duration_minutes} onChange={e => patch(p => ({ ...p, routine: { ...p.routine, duration_minutes: e.target.value ? Math.min(1440, Math.max(1, Number(e.target.value))) : null } }))} /></label>}<label>Preferências ou contexto<textarea maxLength={160} value={plan.routine.preference} onChange={e => patch(p => ({ ...p, routine: { ...p.routine, preference: e.target.value } }))} /></label></>}
 {step === 2 && <><h2>Resultado desejado</h2><label>O que você quer concluir?<textarea maxLength={500} rows={5} value={plan.goal} onChange={e => patch(p => ({ ...p, goal: e.target.value }))} /></label><label>Link para QR (opcional)<input type="url" maxLength={2048} value={plan.qr.url} onChange={e => patch(p => ({ ...p, qr: { url: e.target.value } }))} /></label><p className="miniapp-muted" role="status">{plan.qr.url ? normalizeUrl(plan.qr.url) ? "QR será gerado localmente no dispositivo." : "Informe uma URL HTTP ou HTTPS válida." : "Sem link, o Prisma não exibirá QR."}</p></>}
 {step === 3 && <><h2>Sequência de ações</h2><p>Edite, mova e aceite cada sugestão. Até 30 ações.</p>{sorted.map((action, index) => <div className="miniapp-action-row" key={action.id}><label>Ação {index + 1}<input maxLength={240} value={action.text} onChange={e => setAction(action.id, { text: e.target.value, verb: e.target.value.trim().split(/\s+/)[0]?.slice(0,50) || "Definir" })} /></label><div className="miniapp-action-controls"><button aria-label={`Mover ação ${index + 1} para cima`} disabled={index === 0} onClick={() => move(action.id, -1)}>↑</button><button aria-label={`Mover ação ${index + 1} para baixo`} disabled={index === sorted.length - 1} onClick={() => move(action.id, 1)}>↓</button><select aria-label={`Estado da ação ${index + 1}`} value={action.state} onChange={e => setAction(action.id, { state: e.target.value as Action["state"] })}><option value="suggested">Sugerida</option><option value="accepted">Aceita</option><option value="blocked">Pendente</option><option value="completed">Concluída</option></select><button onClick={() => patch(p => ({ ...p, actions: p.actions.filter(a => a.id !== action.id).map((a, i) => ({ ...a, order: i + 1 })) }))}>Remover</button></div></div>)}<button onClick={addAction} disabled={plan.actions.length >= 30}>Adicionar ação</button></>}
 <div className="miniapp-actions"><button onClick={() => step ? setStep(step - 1) : setScreen("intro")}>Voltar</button><button className="btn btn-primary mini-primary" onClick={() => step < 3 ? setStep(step + 1) : setScreen("result")}>{step < 3 ? "Continuar" : "Ver plano"}</button></div></div><aside className="panel miniapp-panel miniapp-desktop-preview"><h2>Prévia em tempo real</h2><div className="miniapp-actions"><button onClick={() => setView("process")} aria-pressed={view === "process"}>Processo</button><button onClick={() => setView("prisma")} aria-pressed={view === "prisma"}>Prisma</button></div>{sheet}</aside><div className="miniapp-mobile-preview"><h2>Prévia</h2>{sheet}</div></section>}
 {screen === "result" && <section data-print><h1>Revise seu plano</h1><div className="miniapp-actions"><button onClick={() => setView("process")} aria-pressed={view === "process"}>Processo</button><button onClick={() => setView("prisma")} aria-pressed={view === "prisma"}>Prisma</button></div>{sheet}<aside className="panel miniapp-panel"><label>Link para QR (opcional)<input type="url" maxLength={2048} value={plan.qr.url} onChange={e => patch(p => ({ ...p, qr: { url: e.target.value } }))} /></label><p role="status">{plan.qr.url ? normalizeUrl(plan.qr.url) ? "QR gerado no navegador, sem envio do link." : "URL inválida; use HTTP ou HTTPS." : "QR não configurado."}</p><div className="miniapp-actions"><button className="btn btn-primary mini-primary" onClick={() => window.print()}>Imprimir / PDF</button><button onClick={exportJson}>Baixar JSON</button><label>Importar JSON<input type="file" accept=".json,application/json" onChange={importJson} /></label><label><input type="checkbox" checked={save} onChange={e => { setSave(e.target.checked); if (!e.target.checked) localStorage.removeItem(KEY); }} /> Salvar neste dispositivo</label><button onClick={() => { if (confirm("Apagar os dados locais deste Mini App?")) { localStorage.removeItem(KEY); setSave(false); setPlan(fresh()); setScreen("intro"); } }}>Limpar dados</button><button onClick={() => { setScreen("form"); setStep(0); }}>Editar</button></div></aside></section>}{message && <p role="status">{message}</p>}</div>;
}
