import { useEffect, useState, type ChangeEvent } from "react";
import QRCode from "qrcode";

type Task={id:string;text:string;accepted:boolean};
type Plan={version:"1.0.0";name:string;context:string;window:string;goal:string;tasks:Task[];url:string};
const KEY="executar-processo-prisma-v1";
const fresh=():Plan=>({version:"1.0.0",name:"",context:"",window:"",goal:"",tasks:["Definir o resultado","Organizar a sequência","Preparar os materiais"].map((text,i)=>({id:"ACT-"+(i+1),text,accepted:false})),url:""});
const httpUrl=(s:string)=>{try{const u=new URL(s.trim());return ["https:","http:"].includes(u.protocol)?u.toString():""}catch{return ""}};
function valid(x:unknown):x is Plan{if(!x||typeof x!=="object")return false;const p=x as Plan;return p.version==="1.0.0"&&typeof p.name==="string"&&typeof p.context==="string"&&typeof p.goal==="string"&&Array.isArray(p.tasks)&&p.tasks.length<=20&&p.tasks.every(t=>typeof t.id==="string"&&typeof t.text==="string"&&typeof t.accepted==="boolean")&&typeof p.url==="string"}
export function ProcessWorkApp(){
 const [p,setP]=useState(fresh),[step,S]=useState(0),[screen,SS]=useState<"intro"|"form"|"result">("intro"),[view,V]=useState<"process"|"prisma">("process"),[qr,Q]=useState(""),[save,Save]=useState(false),[msg,M]=useState("");
 useEffect(()=>{navigator.serviceWorker?.register("/ferramentas/processo-de-trabalho/sw.js",{scope:"/ferramentas/processo-de-trabalho/"}).catch(()=>{})},[]);
 useEffect(()=>{if(save)try{localStorage.setItem(KEY,JSON.stringify(p))}catch{M("Não foi possível salvar neste dispositivo.")}},[p,save]);
 useEffect(()=>{const u=httpUrl(p.url);if(!u){Q("");return}let ok=true;QRCode.toDataURL(u,{margin:4,width:220,errorCorrectionLevel:"M"}).then(v=>ok&&Q(v)).catch(()=>Q(""));return()=>{ok=false}},[p.url]);
 const patch=(v:Partial<Plan>)=>setP(x=>({...x,...v}));
 const importJson=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!valid(x))throw Error("JSON inválido para MiniAppPlan v1.");setP(x);SS("form");S(3);M("Arquivo importado.")}catch(err){M(err instanceof Error?err.message:"Arquivo inválido.")}finally{e.target.value=""}};
 const exportJson=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="executar-plan-v1.json";a.click();URL.revokeObjectURL(u)};
 const sheet=<article className={"miniapp-sheet "+view}><header><small>EXECUTAR · MINI APP</small><h2>{p.name||"Processo de trabalho"}</h2><p>{p.context||"Contexto a definir"} · {p.window||"Período a definir"}</p></header>{view==="process"?<><h3>Resultado</h3><p>{p.goal||"A DEFINIR"}</p><ol>{p.tasks.map(t=><li key={t.id}>{t.text||"Ação a definir"} <small>{t.accepted?"ACEITA":"SUGERIDA"}</small></li>)}</ol></>:<div className="miniapp-faces"><section><small>FACE 01 · VISÃO</small><h3>{p.goal||"Resultado desejado"}</h3><p>{p.context||"Contexto a definir"}</p></section><section><small>FACE 02 · EXECUÇÃO</small>{p.tasks.map((t,i)=><p key={t.id}>{i+1}. {t.text||"Ação a definir"}</p>)}</section><section><small>FACE 03 · PRÓXIMO PASSO + QR</small>{qr?<img width="120" src={qr} alt="QR gerado localmente"/>:<p>QR opcional</p>}<p>{p.url||"Link não informado"}</p></section></div>}</article>;
 return <main className="miniapp-root"><style>{`.miniapp-root{max-width:1200px;margin:auto;padding:32px 20px;color:var(--cf-fg)}.miniapp-root button,.miniapp-root input,.miniapp-root textarea{font:inherit}.miniapp-root button{min-height:44px;padding:9px 14px;margin:4px;border:1px solid var(--cf-border);border-radius:10px;background:var(--cf-bg);color:inherit}.miniapp-root button:focus-visible,.miniapp-root input:focus-visible,.miniapp-root textarea:focus-visible{outline:3px solid var(--cf-focus)}.miniapp-root label{display:grid;gap:6px;margin:12px 0}.miniapp-root input,.miniapp-root textarea{padding:10px;border:1px solid var(--cf-border);border-radius:8px;background:var(--cf-bg);color:inherit;min-height:44px}.miniapp-main{display:grid;grid-template-columns:1fr 1fr;gap:20px}.miniapp-panel{padding:20px;border:1px solid var(--cf-border);border-radius:16px}.miniapp-sheet{background:#fff;color:#17191f;padding:9mm;min-height:297mm;max-width:760px;margin:16px auto;box-shadow:0 4px 18px #0002}.miniapp-sheet header{border-bottom:2px solid #2865d9}.miniapp-sheet li{padding:10px;border-bottom:1px solid #ddd}.miniapp-sheet small{font-size:10px;color:#555}.miniapp-faces{display:grid;grid-template-rows:repeat(3,99mm)}.miniapp-faces section{border-bottom:1px dashed #aaa;padding:5mm 2mm;overflow:hidden}.miniapp-root img{max-width:100%}.miniapp-actions{display:flex;flex-wrap:wrap;gap:8px}.miniapp-root .mini-primary{background:var(--cf-accent);color:white}@media(max-width:800px){.miniapp-main{grid-template-columns:1fr}}@media print{@page{size:A4;margin:0}.miniapp-root>*:not([data-print]){display:none!important}.miniapp-root{padding:0}.miniapp-sheet{margin:0;width:210mm;max-width:none;height:297mm;box-shadow:none;padding:9mm}.miniapp-faces{grid-template-rows:repeat(3,99mm)}}`}</style>
 {screen==="intro"&&<section><p>EXECUTAR · FERRAMENTAS</p><h1>Processo de Trabalho + Prisma</h1><p>Preencha, revise as ações e imprima uma projeção A4.</p><button className="mini-primary" onClick={()=>{setP(fresh());SS("form");S(0)}}>Criar plano</button><button onClick={()=>{setP({...fresh(),tasks:[]});SS("result")}}>Template vazio</button><label>Importar JSON<input type="file" accept=".json,application/json" onChange={importJson}/></label></section>}
 {screen==="form"&&<section className="miniapp-main"><div className="miniapp-panel"><p>ETAPA {step+1} DE 4</p>{step===0&&<><label>Nome (opcional)<input value={p.name} onChange={e=>patch({name:e.target.value})}/></label><label>Contexto de trabalho<input value={p.context} onChange={e=>patch({context:e.target.value})}/></label></>}{step===1&&<><label>Período do dia<select value={p.window} onChange={e=>patch({window:e.target.value})}><option value="">Selecione</option><option>Manhã</option><option>Tarde</option><option>Noite</option><option>Personalizar</option></select></label></>}{step===2&&<label>Resultado desejado<textarea value={p.goal} onChange={e=>patch({goal:e.target.value})}/></label>}{step===3&&p.tasks.map(t=><label key={t.id}>Ação<input value={t.text} onChange={e=>patch({tasks:p.tasks.map(x=>x.id===t.id?{...x,text:e.target.value}:x)})}/><span><input type="checkbox" checked={t.accepted} onChange={e=>patch({tasks:p.tasks.map(x=>x.id===t.id?{...x,accepted:e.target.checked}:x)})}/> Aceitar sugestão</span></label>)}<div className="miniapp-actions"><button onClick={()=>step?S(step-1):SS("intro")}>Voltar</button><button className="mini-primary" onClick={()=>step<3?S(step+1):SS("result")}>{step<3?"Continuar":"Ver plano"}</button></div></div><aside className="miniapp-panel"><button onClick={()=>V("process")}>Processo</button><button onClick={()=>V("prisma")}>Prisma</button>{sheet}</aside></section>}
 {screen==="result"&&<section data-print><h1>Revise seu plano</h1><button onClick={()=>V("process")}>Processo</button><button onClick={()=>V("prisma")}>Prisma</button>{sheet}<aside className="miniapp-panel"><label>URL para QR (opcional)<input type="url" value={p.url} onChange={e=>patch({url:e.target.value})}/></label><p role="status">{p.url?(httpUrl(p.url)?"QR gerado no navegador.":"URL inválida; use HTTP ou HTTPS."):"QR vazio."}</p><div className="miniapp-actions"><button className="mini-primary" onClick={()=>window.print()}>Imprimir / PDF</button><button onClick={exportJson}>Baixar JSON</button><label>Importar JSON<input type="file" accept=".json,application/json" onChange={importJson}/></label><label><input type="checkbox" checked={save} onChange={e=>{Save(e.target.checked);if(!e.target.checked)localStorage.removeItem(KEY)}}/> Salvar neste dispositivo</label><button onClick={()=>{if(confirm("Apagar dados locais?")){localStorage.removeItem(KEY);Save(false);setP(fresh());SS("intro")}}}>Limpar dados</button><button onClick={()=>SS("form")}>Editar</button></div></aside></section>}{msg&&<p role="status">{msg}</p>}</main>;
}
